### ISSUE TITLE
Invalid UTF-8 label -- Prometheus Error with VTS Exporter. 

### ISSUE THREAD

**Issue by jakirpatel** [vozlt/nginx-module-vts#142] opened 2018-10-30 08:55 UTC
Prometheus Version : v2.4.3
Error message :
`
error while linting: text format parsing error in line 501: invalid label value "\xfftest-api"`

Problem information:

We are having 10 nginx servers with VTS module enabled. Somehow the client is making the wrong http request and nginx is throwing 502 error. In this scenario VTS is capturing the invalid character as well.

Prometheus is collecting the metrics from all nginx servers. So if someone hit the nginx with invalid http host then prometheus is scraping all the metrics even with invalid character. This is causing potential failure at prometheus layer.

Its throwing the error:
`error while linting: text format parsing error in line 501: invalid label value "\xfftest-api"
`
We do have three different layers here Nginx , VTS module and Prometheus. Because of this we are potentially loosing our all metrics.

Is there any solution to have on these? Anyway we can tell the prometheus to remove the metric with invalid label and start functioning as usual . I think prometheus somehow should ignore these kind of metric to be logged in prometheus to avoid the failure of prometheus itself.

**Comment by jakirpatel** [comment] 2018-11-06 01:41
@vozlt Anything we can do for the error that we have got with the VTS..

**Comment by vozlt** [comment] 2021-01-25 14:37
@jakirpatel 
Thanks the bug report.
I merged the [pull/151](https://github.com/vozlt/nginx-module-vts/pull/151).

**Comment by axingblog** [comment] 2022-10-14 08:14
use release [v0.2.1](https://github.com/vozlt/nginx-module-vts/releases/tag/v0.2.1)     ,have same problem

request uri : /ip/%E6%B1%89%E5%AD%97
<img width="806" alt="image" src="https://user-images.githubusercontent.com/5227772/195797179-fbe08b6a-c5da-4c2d-a50f-18b419d48208.png">

**Comment by vozlt** [comment] 2022-10-17 14:46
@axingblog 
Thanks for reporting. I'll check it soon.

**Comment by topicgit** [comment] 2023-02-14 08:27
> @axingblog Thanks for reporting. I'll check it soon.

Has this issue been fixed? I'm facing the same problem with 'invalid UTF-8 label value'.
Thanks.

**Comment by u5surf** [comment] 2023-02-15 00:05
@axingblog 
Hi, I’m a new collaborator for this module.
Thanks for your all bug report!
First of all, sadly we could not reproduce on this behavior with this configuraion which I assumed your reproduced one. I’d like to reproduce this behavior, can you provide your reproduced one? It is possible to clarify what happen in escaping that.
```
nginx_vts_filter_bytes_total{filter="appname::nginx",filter_name="/ip/%E6%B1%89%E5%AD%97",direction="in"} 99
nginx_vts_filter_bytes_total{filter="appname::nginx",filter_name="/ip/%E6%B1%89%E5%AD%97",direction="out"} 314
```

nginx.conf
```

http {
    include       mime.types;
    default_type  application/octet-stream;

    vhost_traffic_status_zone;
    upstream web {
            zone backend 64k;
            server 127.0.0.1:9000;
    }
    server {
        listen       8000;
        location / {
            vhost_traffic_status_filter_by_set_key $request_uri appname::nginx;
            proxy_pass http://web;
        }
    }
    server {
        listen       80;
        gzip off;
        client_max_body_size 100M;
        location /status/ {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format prometheus;
        }
    }
}

```
@topicgit 
Also, if you have any clues(e.g. you have a configuraion which can be reproduced assuredly.) please inform for us🙏

**Comment by u5surf** [comment] 2023-02-15 00:22
https://github.com/vozlt/nginx-module-vts/pull/165

**Comment by u5surf** [comment] 2023-02-15 14:08
`ngx_http_vhost_status_escape_prometheus` seems not to escape the character which is represented by byte sequences between 0x80 - 0x10ffff.

**Comment by u5surf** [comment] 2023-02-15 14:15
@axingblog @topicgit @vozlt @SuperQ 
I will fix it below.

Which is prefer to represent `\\x` encoding format or `%` one?

e.g. request
```
curl http://localhost:8000/ip/姹夊瓧
```

result
```
nginx_vts_filter_bytes_total{filter="appname::nginx",filter_name="/ip/%E5%A7%B9%E5%A4%8A%E7%93%A7",direction="in"} 90
nginx_vts_filter_bytes_total{filter="appname::nginx",filter_name="/ip/%E5%A7%B9%E5%A4%8A%E7%93%A7",direction="out"} 314
```

**Closed** 2023-03-26 21:34 UTC
Labels: bug
