### ISSUE TITLE
Support prometheus metrics with nginx-module-vts

### ISSUE THREAD

**Issue by hnlq715** [vozlt/nginx-module-vts#62] opened 2016-12-09 02:57 UTC
Recently I came across prometheus, and I tried to implement prometheus metrics with nginx-module-vts.

Here is [nginx-vts-exporter](https://github.com/hnlq715/nginx-vts-exporter), which is heavily used in our system.

Hope this can be helpful, and any questions would be pleasure 😆

**Comment by vozlt** [comment] 2016-12-09 05:33
Thank you for publishing your code. 👍 
I would like to add your  nginx-vts-exporter link in nginx-module-vts's README.md if you allow.

**Comment by hnlq715** [comment] 2016-12-09 06:48
sure 😄

**Comment by discordianfish** [comment] 2018-01-08 19:26
Lemme hijack this issue.. @vozlt With prometheus become the defactor standard of metrics exposition, would you be open to add prometheus metrics natively? It's a simple text based format and it wouldn't require users to somehow 'translate' it by using either @hnlq715 exporter or Kubernetes ingress controller which does the same: https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/customization/custom-vts-metrics-prometheus/README.md

**Comment by SuperQ** [comment] 2018-02-21 11:16
This appears to be a dupe of https://github.com/vozlt/nginx-module-vts/issues/58.

**Comment by hnlq715** [comment] 2018-02-21 13:11
Hope this could help you guys, simple lua code generates nginx's prometheus metrics.
https://github.com/hnlq715/nginx-prometheus-metrics

**Comment by nri-pl** [comment] 2018-03-15 14:03
#114

**Comment by vozlt** [comment] 2018-06-01 07:53
That feature has added.
All mertric names are started with `nginx_vts_(*)`.
I can not guarantee that it will work well because I know little about prometheus.
Please test it.
Thanks.

Latest commit: 2f9434f

**Comment by towolf** [comment] 2018-06-05 23:06
@vozlt I've tested this and it seems pretty good. It seems to make https://github.com/hnlq715/nginx-vts-exporter entirely unnecessary. It compared both and replaced just the metric names and it was basically a drop-in replacement. Only some connection states in `nginx_vts_main_connections` seem to differ:

Separate VTS exporter
![image](https://user-images.githubusercontent.com/345210/41007331-90ffe49e-6925-11e8-8bfc-2bb2341f1cab.png)

Native VTS
![image](https://user-images.githubusercontent.com/345210/41007352-b2969ba2-6925-11e8-9719-cfcf245e47d0.png)

Now, for the future, request times sorted into histogram buckets or percentiles would be great.

**Comment by SuperQ** [comment] 2018-06-06 07:20
@towolf Looks good. The connections graph doesn't seem far off, I'm guessing it's a difference of polling jitter.  What scrape interval are you using there? Maybe try speeding it up to something like 5-10s to get higher resolution on the gauge.  Gauges are inherently sensitive to polling jitter.

It would be useful to have some counters, like `nginx_connections_total`.

I sent a couple of PRs to do some best practices cleanup, but otherwise this looks pretty good.

**Comment by discordianfish** [comment] 2018-06-06 08:41
> Now, for the future, request times sorted into histogram buckets or percentiles would be great.
@vozlt Is that something you would be willing to add? I guess it's a bit more complicated and the bucket sizes would need to be configurable. Here are a few words on how it looks like: https://prometheus.io/docs/concepts/metric_types/#histogram

But basically the vts module would have to observe the duration of *each* request and add it to the right bucket. Pre-sampled averages and cut-off samples like exposed right now are unfortunately not enough to get any meaningful averages (see https://github.com/hnlq715/nginx-vts-exporter/issues/43#issuecomment-383077623)

**Comment by vozlt** [comment] 2018-06-07 14:56
@discordianfish I will check out the histogram of prometheus soon.
Thanks.

**Comment by towolf** [comment] 2018-06-10 22:57
Tested this again, and from what I can see at first glance, this works as it should.

Grafana can directly present histogram data as is as a heatmap. And Prometheus can transform histogram buckets into percentiles using [this approximative function](https://prometheus.io/docs/practices/histograms/#quantiles).

I only have sparse data at the moment:

![image](https://user-images.githubusercontent.com/345210/41207246-5d336424-6d12-11e8-88e0-5bf311e1911b.png)

**Comment by draskolnikova** [comment] 2018-10-15 06:53
@vozlt @hnlq715 

I've seen upstreame state `(down|up)` in json format, would you mind to expose that in prometheus format?

**Comment by yangboyd** [comment] 2018-12-06 10:15
> Tested this again, and from what I can see at first glance, this works as it should.
> 
> Grafana can directly present histogram data as is as a heatmap. And Prometheus can transform histogram buckets into percentiles using [this approximative function](https://prometheus.io/docs/practices/histograms/#quantiles).
> 
> I only have sparse data at the moment:
> 
> ![image](https://user-images.githubusercontent.com/345210/41207246-5d336424-6d12-11e8-88e0-5bf311e1911b.png)
> 
> Pretty great, thanks.
@towolf  Would you please share your grafana dashboard?
Thanks a lot!

**Comment by towolf** [comment] 2018-12-06 10:55
@yangboyd sure, [here you go](https://gist.github.com/towolf/c01436fb5991d5fcea85ee1c7cb62030)

But this dashboard is pretty specific for our old Kubernetes ingress setup, which at the time was a stand-alone thing.

But you can check it out, if you want.

**Closed** 2021-01-20 14:18 UTC
Labels: enhancement
